/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.shobair.hospital.view;

import com.shobair.hospital.db.dao.UserDetailsDao;
import com.shobair.hospital.db.dao.UsersDao;
import com.shobair.hospital.db.type.UsersType;
import com.shobair.hospital.db.vo.UserDetailsVo;
import com.shobair.hospital.db.vo.UsersVo;
import com.shobair.hospital.validaton.Validation;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


public class UsersView extends javax.swing.JFrame 
{
public static byte [] imageByte;
  
    public UsersView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFatherName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cUserType = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPassWord = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtImagePath = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("ID");

        jLabel2.setText("UserName");

        jLabel4.setText("passWord");

        jLabel5.setText("UserType");

        cUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "doctor", "nurse" }));
        cUserType.setSelectedIndex(-1);
        cUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUserTypeActionPerformed(evt);
            }
        });

        jLabel6.setText("FirstName");

        jLabel7.setText("FatherName");

        jLabel8.setText("Mobile");

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jButton2.setText("ChooseImage");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(txtMobile))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(217, 217, 217))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cUserType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPassWord))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(56, 56, 56)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtFirstName)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtImagePath))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUserTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cUserTypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       boolean isTextEmpty = Validation.isEmpty(txtid.getText(),txtUserName.getText(),txtPassWord.getText(),txtFirstName.getText(),
              txtFatherName.getText(),txtMobile.getText());
       boolean isEmpty = Validation.isEmpty(cUserType.getSelectedIndex());
       boolean isDigit = Validation.isDigit(txtid.getText(),txtMobile.getText());
       boolean isText  = Validation.isText(txtUserName.getText(),txtPassWord.getText(),txtFirstName.getText(), txtFatherName.getText());
       if(isTextEmpty == true || isEmpty == true)
       {
           JOptionPane.showMessageDialog(null, "plesase enter a valid data");
           return;
       }
       if(isDigit == false || isText == false)
       {
           JOptionPane.showMessageDialog(null, "plesase enter a valid data");
           return;
       }
       
        int id=Integer.valueOf(txtid.getText());
        String UserName=txtUserName.getText();
        String PassWord=txtPassWord.getText();
        UsersType userType=UsersType.getUserTypeByType(cUserType.getSelectedItem().toString());
        UsersVo userVo = new UsersVo();
        userVo.setId(id);
        userVo.setUserName(UserName);
        userVo.setPassword(PassWord);
        userVo.setUserType(userType);
        String firstName=txtFirstName.getText();
        String fatherName=txtFatherName.getText();
        String mobile=txtMobile.getText();
        UserDetailsVo userDetailVo = new UserDetailsVo();
        userDetailVo.setUserVo(userVo);
        userDetailVo.setFirstName(firstName);
        userDetailVo.setFatherName(fatherName);
        userDetailVo.setMobile(mobile);
      //  userDetailVo.setImage(imageByte);
        try {
           //int userCount = UsersDao.getInstance().insert(userVo);
          // int UserDetailsCount = UserDetailsDao.getInstance().insert(userDetailVo);
           int Count = UserDetailsDao.getInstance().insert(userDetailVo);
           if(Count == 1)
           {
               JOptionPane.showMessageDialog(null, "insert successfully");
               Reset();
           }
           else
           {
                JOptionPane.showMessageDialog(null, "insert not successfully");
           }
        } catch (Exception ex) 
        {
            Logger.getLogger(UsersView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       boolean isTextEmpty = Validation.isEmpty(txtid.getText());
       boolean isDigit = Validation.isDigit(txtid.getText());
        if(isTextEmpty == true )
       {
           JOptionPane.showMessageDialog(null, "plesase enter a valid data");
           return;
       }
       if(isDigit == false)
       {
           JOptionPane.showMessageDialog(null, "plesase enter a valid data");
           return;
       }
       int id=Integer.valueOf(txtid.getText());
       UsersVo uservo = new UsersVo();
       uservo.setId(id);
       UserDetailsVo userDetailVo = new UserDetailsVo();
       userDetailVo.setUserVo(uservo);
        
        try {
 
           int Count = UserDetailsDao.getInstance().delete(userDetailVo);
           if(Count == 1)
           {
               JOptionPane.showMessageDialog(null, "Delete successfully");
               Reset();
           }
           else
           {
                JOptionPane.showMessageDialog(null, "Delete not successfully");
           }
        } catch (Exception ex) 
        {
            Logger.getLogger(UsersView.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

       boolean isTextEmpty = Validation.isEmpty(txtid.getText(),txtUserName.getText(),txtPassWord.getText(),txtFirstName.getText(),
       txtFatherName.getText(),txtMobile.getText());
       boolean isEmpty = Validation.isEmpty(cUserType.getSelectedIndex());
       boolean isDigit = Validation.isDigit(txtid.getText(),txtMobile.getText());
       boolean isText  = Validation.isText(txtUserName.getText(),txtPassWord.getText(),txtFirstName.getText(), txtFatherName.getText());
        if(isTextEmpty == true || isEmpty == true)
       {
           JOptionPane.showMessageDialog(null, "plesase enter a valid data");
           return;
       }
       if(isDigit == false || isText == false)
       {
           JOptionPane.showMessageDialog(null, "plesase enter a valid data");
           return;
       }
       int id=Integer.valueOf(txtid.getText());
        String UserName=txtUserName.getText();
        String PassWord=txtPassWord.getText();
        UsersType userType=UsersType.getUserTypeByType(cUserType.getSelectedItem().toString());
        UsersVo userVo = new UsersVo();
        userVo.setId(id);
        userVo.setUserName(UserName);
        userVo.setPassword(PassWord);
        userVo.setUserType(userType);
        String firstName=txtFirstName.getText();
        String fatherName=txtFatherName.getText();
        String mobile=txtMobile.getText();
        UserDetailsVo userDetailVo = new UserDetailsVo();
        userDetailVo.setUserVo(userVo);
        userDetailVo.setFirstName(firstName);
        userDetailVo.setFatherName(fatherName);
        userDetailVo.setMobile(mobile);
        //userDetailVo.setImage(imageByte);
       try 
       {
            int Count = UserDetailsDao.getInstance().update(userDetailVo);
           if(Count == 1)
           {
               JOptionPane.showMessageDialog(null, "Update successfully");
               Reset();
           }
           else
           {
                JOptionPane.showMessageDialog(null, "Update not successfully");
           }
        } catch (Exception ex) 
        {
            Logger.getLogger(UsersView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    JFileChooser jFileChooser  = new JFileChooser();
   
    jFileChooser.showOpenDialog(null);
   File file = jFileChooser.getSelectedFile();
   String ImagePath = file.getAbsolutePath();
   txtImagePath.setText(ImagePath);
   try
   {
         File file2 = new File(ImagePath);
        FileInputStream fis = new FileInputStream(file2);
        ByteArrayOutputStream boas = new ByteArrayOutputStream();
        byte [] length = new byte[1024];
        for(int i;(i = fis.read(length))!= -1;)
        {
            boas.write(length, 0, i);
        }
        imageByte = boas.toByteArray();
   }
    catch(Exception ex)
    {
        
       
        
    }
    }//GEN-LAST:event_jButton2ActionPerformed
protected void Reset()
{
    txtid.setText("");
    txtUserName.setText("");
    txtPassWord.setText("");
    txtFirstName.setText("");
    txtFatherName.setText("");
    txtMobile.setText("");
    cUserType.setSelectedIndex(-1);
}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox<String> cUserType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtFatherName;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtImagePath;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtPassWord;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
